CREATE TABLE IF NOT EXISTS USERS( 
	ID   SERIAL PRIMARY KEY UNIQUE,
	UID  TEXT UNIQUE,
	EMAIL TEXT UNIQUE,
	USERNAME TEXT UNIQUE, 
	PASS TEXT
);
-- INSERT INTO USERS (UID,EMAIL,USERNAME,PASS) VALUES(?,?,?,?)
-- UID = md5(USERNAME+randint())
-- INSERT INTO USERS (UID,EMAIL,USERNAME,PASS) VALUES('jim','a','pac','ninja') IF CONFLICT THEN DO NOTHING returning true ELSE returning false END IF

CREATE TABLE IF NOT EXISTS BOTS( 
	BID   SERIAL PRIMARY KEY UNIQUE,
	UID  TEXT UNIQUE,
	ALIVE BOOLEAN,
	SERVER TEXT,
	CHANNEL  TEXT
);
-- INSERT INTO BOTS (UID,SERVER,CHANNEL) VALUES(?,?,?)
CREATE TABLE IF NOT EXISTS PLUGINS(
	BID   INTEGER,
	UID  TEXT,
	PLUGIN TEXT
); 
-- INSERT INTO PLUGINS (BID,PLUGIN) VALUES(?,?)

-- SELECT BID,SERVER,CHANNEL FROM BOTS WHERE UID = ?;
-- 1|freenode|#ezirc
-- 2|freenode|#oodnet

-- SELECT BID,PLUGIN FROM BOTS WHERE BID = 1;
-- 1|github
-- 2|timein